### ISSUE TITLE
first js and python demos result in blank screens when running the js/py cells

### ISSUE THREAD

**Issue by richiverse** [iodide-project/iodide#1117] opened 2018-10-31 15:38 UTC
Short summary of the bug. Please include the IODIDE version number where you found the bug - if you are just running locally (building for dev or prod) you can put MASTER

Running the following intro web demos:
Running the first js cell: https://iodide.io/iodide-examples/what-a-web-notebook-looks-like.html
or the first python cell (after running previous cells successfully): 

both result in a completely blank screen
### What I Did

I ran all the first few cells until the code cells for `py` or `js` were run. Then my screen when blank

### What I Expected

I expected to see output form js, python

### What Happened 

screen went blank

### (OPTIONAL) notebook that reproduces bug 

console logs:

Before running js cell:
![image](https://user-images.githubusercontent.com/2671102/47799257-46a8b480-dd00-11e8-8dc3-40dd334e75c2.png)

After running first js cell:
![image](https://user-images.githubusercontent.com/2671102/47799512-cb93ce00-dd00-11e8-8d72-6fc8a2ed2c84.png)

before running py cell:
![image](https://user-images.githubusercontent.com/2671102/47799608-039b1100-dd01-11e8-9ee4-240c2f58d817.png)

after running py cell:
![image](https://user-images.githubusercontent.com/2671102/47799707-334a1900-dd01-11e8-8dfe-e9bcace98984.png)
continued
![image](https://user-images.githubusercontent.com/2671102/47799747-452bbc00-dd01-11e8-9b8b-69c26a47b8dd.png)

**Comment by iFlameing** [comment] 2018-10-31 18:10
@richiverse  Which browser you are using because when I am running the same blocks it is not giving me the error you specified.when I run both first blocks in js and python.
![screenshot from 2018-10-31 23-37-57](https://user-images.githubusercontent.com/33936987/47809155-3b886f80-dd66-11e8-883f-38d03b2acc86.png)
![screenshot from 2018-10-31 23-38-23](https://user-images.githubusercontent.com/33936987/47809159-404d2380-dd66-11e8-8311-22b4710c5036.png)

**Comment by richiverse** [comment] 2018-10-31 18:56
![image](https://user-images.githubusercontent.com/2671102/47811797-0e639f00-dd1d-11e8-83b4-0f0c90abf068.png)

On ubuntu 16.04

**Comment by bcolloran** [comment] 2018-11-07 20:41
@mdboom any thoughts on this? is this a wontfix bug in the old deployment?

**Comment by mdboom** [comment] 2018-11-07 20:49
I can't reproduce this, even when going back to Firefox 62.  This leads me to wonder if perhaps an extension is somehow getting in the way.  @richiverse : Can you try running firefox without any extensions (`firefox --safe-mode`) and seeing if you can still reproduce?

**Comment by iFlameing** [comment] 2018-11-07 21:10
I am also using the firefox 62 but it is not showing error as specified.

**Closed** 2018-11-27 18:53 UTC
Labels: wontfix
