### ISSUE TITLE
Feature request: add plugin languages to cell menu

### ISSUE THREAD

**Issue by louisabraham** [iodide-project/iodide#839] opened 2018-09-05 13:13 UTC
For example, on https://iodide.io/pyodide-demo/python.html, one has to press the "p" key to change a cell to Python.

It is confusing to users as most try to click on the cell menu and they don't see the language they are looking for.

**Comment by bcolloran** [comment] 2018-09-06 19:49
dupe of #830

**Closed by bcolloran** 2018-09-06 19:49 UTC
