### ISSUE TITLE
[bug] dragging Editor Scrollbar not working 

### ISSUE THREAD

**Issue by runsun-edu** [iodide-project/iodide#1618] opened 2019-03-13 14:38 UTC
Short summary of the bug. Please include the IODIDE version number where you found the bug - if you are just running locally (building for dev or prod) you can put MASTER

### What I Did

Open the top 6 examples to see code. Try to scroll code by dragging the scrollbar.

### What I Expected

Scrolling

### What Happened 

For the top-3: They open in the the **Explore** mode ---

 * "A Brief Tour ..." : can't scroll on Chrome; On Microsoft Edge: scrollable the 1st time, failed since then 
 * "The Lorenz ..." : Unscrollable on both Chrome and Edge (Note it can't open in the **Report** mode). 
 * "Pyodide: ..." : Unscrollable on both Chrome and Edge. Note: on Edge, this is opened immediately after the "A Brief Tour ..." is closed. 

For the bottom 3: They opened in the **Report** mode, so they are changed to **Explore** mode to see code  ---

All 3 examples,  "World Happiness Report ", "Peering into the Unknown", "Eviction Notice by SF ...", have normal scrollable bar. 

### (if applicable) notebook that reproduces bug 

Top 3 --- Unscrollable:
https://alpha.iodide.io/notebooks/154/
https://iodide.io/notebooks/34/
https://iodide.io/notebooks/300/

Bottom 3 --- Scrollable in the **Explore** mode: 
https://iodide.io/notebooks/193/?viewMode=report
https://iodide.io/notebooks/194/?viewMode=report
https://iodide.io/notebooks/144/?viewMode=report

**Comment by runsun-edu** [comment] 2019-03-13 14:42
Further finding:

**Comment by wlach** [comment] 2019-03-13 15:10
I have noticed this as well. @bcolloran, do you have any ideas?

**Comment by bcolloran** [comment] 2019-03-13 16:34
Thanks @runsun-edu for this detailed bug report! This is definitely a bad bug :-(

Wow, this is tricky. I really have no idea what is going on, and I cannot reproduce using FF or Chromium on Ubuntu. @hamilton can you take a look to see if you can reproduce on Mac?

I suspect this is some kind of weird edge case in CodeMirror, which I believe does some king of internal magic to handle scrolling.

**Comment by hamilton** [comment] 2019-03-13 16:45
I can reproduce this.

**Comment by hamilton** [comment] 2019-03-13 16:45
For clarity, it's not that my scrollwheel on my mouse doesn't work - it's that I cannot click on the scroll bar and move it. This is a bug we've probably had forever, but I never click on scroll bars!

**Comment by bcolloran** [comment] 2019-03-13 16:52
Oh thank you @hamilton, i overlooked that important detail, my bad. Ok, yes, I can reproduce.

**Comment by wlach** [comment] 2019-03-13 17:07
> Oh thank you @hamilton, i overlooked that important detail, my bad. Ok, yes, I can reproduce.

Rats, I was hoping that you would immediately know what was going on. 😄 

![Screen Shot 2019-03-13 at 1 05 24 PM](https://user-images.githubusercontent.com/20569/54299239-def95480-4590-11e9-9377-d97362b76404.png)

I forgot to mention that I noticed yesterday when investigating this issue that it seemed like the vertical scrollbar had `pointer-events: none` assigned to it. If I delete that property, it seems to work again.

**Comment by wlach** [comment] 2019-03-18 22:10
This bug is very annoying on machines without an easily-accessible scroll wheel / touch scroll (e.g. my Linux laptop), it would be nice to be able to fix it sooner than later.

**Comment by bcolloran** [comment] 2019-03-18 22:28
@wlach do you see this on FF and Chromium? Dragging scrollbars seems to work on FF ubuntu for me, but not on chromium

**Comment by wlach** [comment] 2019-03-18 22:41
> @wlach do you see this on FF and Chromium? Dragging scrollbars seems to work on FF ubuntu for me, but not on chromium

It's broken on both for me (using Fedora). On Mac it appears to work on Firefox (Nightly) but not on Chrome. 

Very strange.

**Comment by bcolloran** [comment] 2019-08-19 17:43
fixed via #2117

**Closed by bcolloran** 2019-08-19 17:43 UTC
