### ISSUE TITLE
new HistoryPane does not seem to update when new history items are added

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#424] opened 2018-03-02 15:51 UTC
Steps to reproduce:

1. go to [this example notebook](https://iodide-project.github.io/iodide-examples/what-a-web-notebook-looks-like.html)
2. open the history pane in the top right corner
3. click the "run all cells" button (the fast-forward icon)
4. observe that nothing is added to history pane. Then click the x
5. open the history pane again. The state is finally updated.

![mar-02-2018 07-48-31](https://user-images.githubusercontent.com/95735/36907840-797de8e8-1dee-11e8-9106-f3dc177c2f16.gif)

**Comment by hamilton** [comment] 2018-03-02 16:07
fwiw this may have also been a bug before #408 was merged. The Declared Variables Pane updates as expected.

**Comment by bcolloran** [comment] 2018-03-02 19:11
i'm pretty sure this existed before #408. I think it's just about how/when we feed those props to the history pane, and when it triggers a react update

**Comment by djbarnwal** [comment] 2018-03-10 13:47
So I was going through the code briefly and it came to my notice that the reducer was [mutating the state](https://github.com/iodide-project/iodide/blob/2439821725487e6b632419bd6cc54fab51a2dce8/src/reducers/cell-reducer.js#L141-L145). The `Object.assign()` function creates a shallow copy. This has been mentioned in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

> For deep cloning, we need to use other alternatives because Object.assign() copies property values. If the source value is a reference to an object, it only copies that reference value.

I will send a PR to fix this issue.

**Comment by imshubhamsingh** [comment] 2018-03-10 15:24
I checked it, the data coming from reducer through mapStateToProps is correct, The problem is that somehow the history data is being persisted. Then I thought there must be some bug in Drawer component of material-ui. But that also working fine as I recreated a scenario in [codesandbox](https://codesandbox.io/s/64v8qkro1n).

**Comment by hamilton** [comment] 2018-03-10 15:26
Great catch @djbarnwal!

**Comment by bcolloran** [comment] 2018-03-11 00:10
fixed by #470

**Closed by bcolloran** 2018-03-11 00:10 UTC
Labels: UI, bug, good first issue
