### ISSUE TITLE
fetch cell should delay execution of the next cell until all scripts are loaded

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#2115] opened 2019-08-01 00:19 UTC
the notebooks below seem to demonstrate a race-ish condition with the fetch cell. it looks like plotly has not yet loaded fully (and thus is not available for import) if the python cell is run immediately after it.

to fix this and similar issues, the fetch cell should delay execution of the next cell until all scripts are loaded. there must be some kind of event we can watch for this

https://definitely-staging.iodide.io/notebooks/72/
https://definitely-staging.iodide.io/notebooks/73/

@mdboom thanks for finding this

**Comment by hamilton** [comment] 2019-08-01 01:15
Hmm, must do a dynamic import. I don’t think we are catching those but we
definitely should.

**Comment by wlach** [comment] 2019-08-06 17:07
This is similar (but not the same) as #1278.

**Comment by wlach** [comment] 2019-11-05 13:56
This actually was just a duplicate of #1278.

**Closed by wlach** 2019-11-05 13:56 UTC
