### ISSUE TITLE
eslint error on windows.

### ISSUE THREAD

**Issue by oxmap** [iodide-project/iodide#695] opened 2018-07-03 12:36 UTC
On windows when run `npm start` log errors such as
`error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`
This lines of code annoying because there are many lines. I disabled it by "linebreak-style": 0 in .eslintrc.

Question is. Is that correct and i need PR this, or on Unix another way?

**Comment by wlach** [comment] 2018-07-03 15:43
I wonder if the problem is the `-f unix` here, in the call to eslint: https://github.com/iodide-project/iodide/blob/master/package.json#L12

There's a long stackoverflow thread here, seemingly without a definitive answer (though I didn't read it too closely):
https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style

**Comment by djbarnwal** [comment] 2018-07-03 15:53
@oxmap Add the following rule `"linebreak-style": ["error", "windows"]` in the `.eslintrc.js` file in order to avoid linebreak style errors in windows.

**Comment by wlach** [comment] 2018-07-03 17:47
It would be best if we didn't ask people to manually modify `.eslintrc`, as that's a checked in file.

According to @edmorley, it's likely that @oxmap has a different git configuration than a project like this expects, he recommends adding/changing this in their global git configuration:

```
[core]
eol = lf
autocrlf = false
```

To avoid this problem coming up on our end, we could specify a .gitattributes file like treeherder has:

https://github.com/mozilla/treeherder/blob/master/.gitattributes

**Comment by hamilton** [comment] 2018-07-03 18:40
@wlach that sounds like a good idea. Do you recommend we just bring in that particular .gitattributes file?

**Comment by oxmap** [comment] 2018-07-04 03:09
@wlach so editing git configuration worked only when clone repo again. But it is worked. So i stil open this issue because of we need gitatributes or something like that.

**Comment by gmkhussain** [comment] 2018-09-11 14:42
Open `package.json`, added following rules under rules line:

```javascript
"rules": {
  "linebreak-style": 0,
  "global-require": 0,
  ...
``` 

for VScode users: click the option at the bottom-right of the window and set it to `LF` from `CRLF`
errors will fixed for me

**Comment by bcolloran** [comment] 2019-01-23 07:40
not sure there is an issue to fix here, closing

**Closed by bcolloran** 2019-01-23 07:40 UTC
Labels: s04: medium
