### ISSUE TITLE
pandas tables getting truncated in reps in Firefox

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/iodide#2458] opened 2019-11-19 21:27 UTC
see https://definitely-staging.iodide.io/notebooks/221/

using a fixed height seems ok, but html based reps should certainly be able to use the whole horizontal space -- for a table this narrow, horizontal scrolling should definitely not be required

**Comment by CruiseDevice** [comment] 2019-11-21 07:15
Does this mean that the table should occupy entire width of the console? And when the columns exceed the console width, there should be scrolling. right?

**Comment by bcolloran** [comment] 2019-11-21 22:09
that's correct (i'll also add that the tables need not expand to fill the whole width)

**Comment by wlach** [comment] 2019-12-04 17:53
hmm, I actually am not seeing the problem you seem to be describing on my machine: 

![image](https://user-images.githubusercontent.com/20569/70167508-e1f32280-1694-11ea-9079-70a8fac90c79.png)

Can you post a screenshot of what you're seeing? And also what version of Firefox and OS you're using. This sounds suspiciously like a Firefox layout bug

**Comment by bcolloran** [comment] 2019-12-04 18:50
yep it's a firefox layout bug, as described here:
https://stackoverflow.com/a/59050187
https://stackoverflow.com/questions/39738265/firefox-displays-unnecessary-horizontal-scrollbar

firefox 70.0.1 linux mint:
![image](https://user-images.githubusercontent.com/2380975/70171380-76548980-1683-11ea-984a-3e363216ab9f.png)

chromium 78.0.3904.108, linux mint:
![image](https://user-images.githubusercontent.com/2380975/70171408-82404b80-1683-11ea-9360-8270c6e52738.png)

**Comment by wlach** [comment] 2019-12-04 20:00
I filed an actual Firefox bug for this so we can hopefully at some point fix the root cause: https://bugzilla.mozilla.org/show_bug.cgi?id=1601409

**Comment by wlach** [comment] 2019-12-05 22:07
Fixed by #2509

**Closed by wlach** 2019-12-05 22:07 UTC
