### ISSUE TITLE
uncaught exception with scrolling to cell

### ISSUE THREAD

**Issue by hamilton** [iodide-project/iodide#415] opened 2018-03-02 01:02 UTC
Error around `scrollToCellIfNeeded`

```
cell-reducer-utils.js:24 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at scrollToCellIfNeeded (file:///Users/hamiltonulmer/Code/mozilla/iodide/dev/iodide.dev.js:79932:21)
    at cellReducer (file:///Users/hamiltonulmer/Code/mozilla/iodide/dev/iodide.dev.js:65940:100)
    at reducers.reduce (file:///Users/hamiltonulmer/Code/mozilla/iodide/dev/iodide.dev.js:65668:59)
    at Array.reduce (<anonymous>)
    at file:///Users/hamiltonulmer/Code/mozilla/iodide/dev/iodide.dev.js:65668:42
    at dispatch (file:///Users/hamiltonulmer/Code/mozilla/iodide/dev/iodide.dev.js:45133:22)
    at Object.dispatch (file:///Users/hamiltonulmer/Code/mozilla/iodide/dev/iodide.dev.js:65644:7806)
    at Object.dispatcher.(anonymous function).params [as selectCell] (file:///Users/hamiltonulmer/Code/mozilla/iodide/dev/iodide.dev.js:12209:95)
    at UserTask.callback (file:///Users/hamiltonulmer/Code/mozilla/iodide/dev/iodide.dev.js:12348:16)
    at HTMLUnknownElement.boundFunc (file:///Users/hamiltonulmer/Code/mozilla/iodide/dev/iodide.dev.js:38655:9)
```

**Comment by imshubhamsingh** [comment] 2018-03-11 06:45
@hamilton I've a temporary fix for it as of now. The main problem is that we are not doing anything for asynchronous codes. So while adding the cell into the nodebook `tasks.addCellBelow` dispatches two function simultaneously because of which the error is showing. The cell is created and selected at the same time, not one after the other. We should really add **redux-thunk** to the project, It'll solve this problem as well as the usage of iodide-api in future.

**Comment by bcolloran** [comment] 2018-03-12 00:32
@imshubhamsingh thanks for looking into this issue!

I think there is something deeper going on here --

i believe dispatch in Redux is synchronous: https://stackoverflow.com/questions/43276291/is-store-dispatch-in-redux-synchronous-or-asynchronous . At least in the Redux store, the reducer will in fact first create the cell and then select it sequentially, not at the same time. I think the problem is likely that we change the store twice in rapid succession before React has a chance to actually draw the the new DOM objects.

What I find very puzzling here is that `tasks.addCellBelow` works _fine_ if you use the kbd shortcut `B` from command mode, but that the task throws an error when launched from a menu click. This strikes me as quite weird, and as an opportunity to learn something  interesting. @hamilton do you have any ideas about why the kbd shortcut might behave differently than the menu click?

In anycase, i think the correct solution here is to make the `scrollToCellIfNeeded` function the responsibility of the CellContainer component, not the cell reducer; and moreover, that the CellContainer should fire `scrollToCellIfNeeded` in it's `componentDidMount()` and `componentDidUpdate()` methods:

https://developmentarc.gitbooks.io/react-indepth/content/life_cycle/update/postrender_with_componentdidupdate.html

This will (a) ensure that the DOM element exists (b) allow us to simplify the reducer, the selectCell action, and the cell-reducer-utils. it should also make scrollToCellIfNeeded work better in general-- the way it's implemented in the CELL_UP/CELL_DOWN reducers is a hack and it's been bugging me,

**Comment by bcolloran** [comment] 2018-04-25 00:06
related to #321

**Comment by hamilton** [comment] 2018-05-31 18:09
@bcolloran do you know the status on this bug?

**Comment by bcolloran** [comment] 2018-05-31 18:13
i would say: also on hold pending iframe architecture/ui experiment

**Comment by bcolloran** [comment] 2018-07-09 00:03
fixed in iframe-2

**Closed by bcolloran** 2018-07-09 00:03 UTC
Labels: bug
