### ISSUE TITLE
Erronous error message when loading local file

### ISSUE THREAD

**Issue by louisabraham** [iodide-project/iodide#816] opened 2018-08-29 14:39 UTC
I'm developing support for OCaml (it works but `printf` and stderr from OCaml currently print to the Javascript debugger console).

My code is like that:

```
{
  "languageId": "ml",
  "displayName": "ocaml",
  "codeMirrorMode": "mllike",
  "keybinding": "o",
  "url": "ocaml_eval.js",
  "module": "evaluator",
  "evaluator": "execute",
  "pluginType": "language"
}
```

When I open a local notebook and launch it, the console shows:

`XML Parsing Error: not well-formed Location: file:///Users/louisabraham/domical/ocaml_eval.js Line Number 1, Column 1:`

I solved my problem with `python -m http.server`, but it would be awesome to be able to load local files :)

**Comment by mdboom** [comment] 2018-08-29 16:01
First let me say that the OCaml thing itself sounds really awesome!  Do you have a github repo for it?  Please share as soon as you're ready.

I assume here that you are loading your iodide `.html` from the local filesystem as well, and that it's in the same directory as your `ocaml_eval.js`?  Have you tried inserting `./` in front of `ocaml_eval.js`?  That works for me when I test pyodide locally.

Are you using Firefox or Chrome?

**Comment by louisabraham** [comment] 2018-08-29 20:41
The bug is that

```
XML Parsing Error: not well-formed
Location: file:///Users/louisabraham/domical/eval.js
Line Number 1, Column 1:
```

is printed to stderr in the console even if loading the file `eval.js` or `./eval.js` works.

**Comment by mdboom** [comment] 2018-08-29 20:44
Ah, I see.  I don't know the solution to that, but I've seen it before.  I think it's because we are using XMLHttpRequest to load something that isn't XML (it's Javascript).

@hamilton: Thoughts?

**Comment by louisabraham** [comment] 2018-08-29 21:35
Since you asked, my code is [online](http://github.com/louisabraham/domical) with a [demo](https://louisabraham.github.io/domical/ocaml.html).

**Comment by mdboom** [comment] 2018-08-29 21:41
Thanks for sharing that.  That's really cool.

**Comment by mdboom** [comment] 2018-08-29 22:09
I think this may be fixed in the current version.  Can you update and try again?

**Comment by bcolloran** [comment] 2018-10-05 06:33
could not reproduce, so this seems to have been fixed.
see https://extremely-alpha.iodide.io/notebooks/30

**Closed by bcolloran** 2018-10-05 06:33 UTC
